name: whatsapp_coded_with_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.4
  cached_network_image: ^3.3.0
  camera: ^0.10.5+8
  emoji_picker_flutter: ^1.6.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  photo_manager: ^2.8.1
  story_view: ^0.16.0
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
